language: php
dist: xenial
sudo: false

php:
  - 7.4

services:
  - memcached
  - redis-server

cache:
  directories:
    - ${HOME}/.composer/cache

env:
  global:
    - COMPOSER_UPDATE_FLAGS="--no-interaction --no-suggest --prefer-dist"
    - MEMCACHED_HOST="127.0.0.1"
    - REDIS_HOST="127.0.0.1"

before_install:
  - printf "\n" | pecl install --force apcu redis
  - echo "apc.enable_cli=1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo "extension=memcached.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - travis_retry composer self-update

before_script:
  - travis_retry composer update ${COMPOSER_UPDATE_FLAGS}

script:
  - vendor/bin/phpunit

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover phpunit/coverage/clover.xml;
