language: php
dist: trusty
sudo: false

php:
  - 7.1
  - 7.2

services:
  - memcached-server
  - redis-server

cache:
  directories:
    - ${HOME}/.composer/cache

env:
  global:
    - COMPOSER_UPDATE_FLAGS="--no-interaction --no-suggest --prefer-dist"
    - COVER_PHP_VERSION="7.1"
    - MEMCACHED_HOST="127.0.0.1"
    - REDIS_HOST="127.0.0.1"

before_install:
  - printf "\n" | pecl install --force apcu redis
  - echo "apc.enable_cli=1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo "extension=memcached.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - travis_retry composer self-update
  - if [ "${TRAVIS_PHP_VERSION}" != "${COVER_PHP_VERSION}" ]; then
      phpenv config-rm xdebug.ini
    ;fi

before_script:
  - travis_retry composer update ${COMPOSER_UPDATE_FLAGS}

script:
  - vendor/bin/phpunit

after_script:
  - if [ "${TRAVIS_PHP_VERSION}" == "${COVER_PHP_VERSION}" ]; then
      wget https://scrutinizer-ci.com/ocular.phar &&
      php ocular.phar code-coverage:upload --format=php-clover phpunit/coverage/clover.xml;
    fi
