version: '3'

services:

  ## PHP Container ###########
  php-fpm:
    build:
      context: .
      dockerfile: ./php-fpm/Dockerfile
    environment:
      - XDEBUG_CONFIG=idekey=PHPSTORM
      - PHP_IDE_CONFIG=serverName=localhost
    env_file:
      - .env
    extra_hosts:
      - XDEBUG_HOST:${XDEBUG_HOST}
    volumes:
      - ./:/var/www
    depends_on:
      - redis

  ## Redis Container ###########
  redis:
    image: redis:4.0-alpine
